// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKY1utR6gZniMiJj45eGJdeWfVCWv3nAY',
    appId: '1:482166655146:web:dc0eb6ba1508242c2ee8d3',
    messagingSenderId: '482166655146',
    projectId: 'stuatt-sa77muk',
    authDomain: 'stuatt-sa77muk.firebaseapp.com',
    storageBucket: 'stuatt-sa77muk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX2GTPcL0IJeqhjytsDPFK1X4SOQVnwv0',
    appId: '1:482166655146:android:8b8400306a7e279d2ee8d3',
    messagingSenderId: '482166655146',
    projectId: 'stuatt-sa77muk',
    storageBucket: 'stuatt-sa77muk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCga3AsqZ7Y4FXK7XxuO0uKTScCOrNTf5Y',
    appId: '1:482166655146:ios:1370590b0d0417a12ee8d3',
    messagingSenderId: '482166655146',
    projectId: 'stuatt-sa77muk',
    storageBucket: 'stuatt-sa77muk.appspot.com',
    iosClientId: '482166655146-b3tfu4rhmfsd1jfvrlso8qak2amkl2jl.apps.googleusercontent.com',
    iosBundleId: 'com.example.codehive.stuatt',
  );
}
